name: alberta_grid
version: '1.0.0'
config-version: 2
profile: alberta_grid
model-paths: [models]
test-paths: [tests]
models:
  alberta_grid:
    +materialized: table
    staging:
      +schema: staging
    marts:
      +schema: marts
